version: '3.7'

services:
  # Backend api
  smart-brain-api:
    container_name: backend
    # image: node:12.18.2
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain-api
    environment:
      POSTGRES_URI: postgres://daylan:secret@postgres:5432/smart-brain-docker
      REDIS_URI: redis://redis:6379
    links:
      - postgres
      - redis
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/smart-brain-api

  #Postgres
  postgres:
    environment:
      POSTGRES_USER: daylan
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
    build: ./postgres
    ports:
      - "5431:5432"
  # Redis

  redis:
    image: "redis"
    ports:
      - "6380:6379"

